/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "STM32F103X6.h"
#include "STM32F103_GPIO_Driver.c"
#include "STM32F103_SPI_Driver.c"
#include "STM32F103_UART_Driver.c"
#include "STM32F103_I2C_Driver.c"
#include "I2C_EEPROM.c"
/* ================================= Global Variables and DataTypes ================================= */




/*
 * =====================================
 * 		Global Functions
 * =====================================
 */
void WAIT_ms(uint32_t t){
	uint32_t i,j;
	for(i=0;i<t;i++){
		for(j=0;j<255;j++);
	}
}


void clock_init(void)
{

	//enable clock for GPIOB
	RCC_GPIOB_CLOCK_EN();
	//enable clock for Alternative IO
	RCC_AFIO_CLOCK_EN();

}

/*
 * =====================================
 * 		CallBack Functions
 * =====================================
 */



/*
 * =====================================
 * 		Configuration Functions
 * =====================================
 */



int main(void)
{

	clock_init();

	I2C_EEPROM_Init();
	uint8_t W_Data[7] = {0x1,0x2,0x3,0x4,0x5,0x6,0x7};
	uint8_t R_Data[7]= {0};



	I2C_EEPROM_Write_Data(0xAF, W_Data, 7);
	I2C_EEPROM_Read_Data(0xAF, R_Data, 7);

	W_Data[0] = 0xA;
	W_Data[1] = 0xB;
	W_Data[2] = 0xC;
	W_Data[3] = 0xD;

	I2C_EEPROM_Write_Data(0xFFF, W_Data, 4);
	I2C_EEPROM_Read_Data(0xFFF, W_Data, 4);






    /* Loop forever */
	for(;;);
}
