/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include<stdint.h>
#include<stdlib.h>
typedef volatile unsigned int vuint32_t;
//GPIOA registers
#define GPIOA_BASE 		0x40010800 //base address of Port A
#define GPIOA_CRH 		*(volatile uint32_t*) (GPIOA_BASE+0x04)
#define GPIOA_ODR 		*(volatile uint32_t*) (GPIOA_BASE+0x0C)
#define GPIOA_CRL		*(volatile uint32_t *)(GPIOA_BASE + 0x00)

// RCC registers
#define RCC_BASE 		0x40021000 //base address of RCC
#define RCC_APB2ENR 	*(volatile uint32_t*) (RCC_BASE+0x18)

//external interrupt registers
#define EXTI_BASE		0x40010400
#define EXTI_IMR		*((volatile uint32_t*)(EXTI_BASE + 0x00))
#define EXTI_RTSR		*((volatile uint32_t*)(EXTI_BASE + 0x08))
#define EXTI_PR			*((volatile uint32_t*)(EXTI_BASE + 0x14))

//AFIO
#define AFIO			0x40010000
#define AFIO_EXTICR1	*((volatile uint32_t*)(AFIO + 0x08))

//NVIC ISER registers
#define NVIC_ISER0		*((volatile uint32_t*)(0xE000E100))

void GPIO_init(){
	//init GPIOA pin 13
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	//init GPIOA pin 0
	GPIOA_CRL |= (1<<2);
	//Configure PortA 0 to accept external interrupt from EXTI0
	AFIO_EXTICR1  = 0;
}

void clock_init(){
	//enable ABP2 clock register
	//enable IO port A clock "IOPAEN"
	RCC_APB2ENR |= 1<<2 ;
	//enable Alternate function IO clock"AFIOEN"
	RCC_APB2ENR |= 1<<0 ;
}

void EXTI_init(){
	//on rising edge
	EXTI_RTSR |= 1<<0;
	//enable interrupt mask EXTI on line 0
	EXTI_IMR |= 1<<0;
}

int main(void)
{
	clock_init();
	GPIO_init();
	EXTI_init();
	//enable NVIC IRQ 6 <<>> EXTI0
	NVIC_ISER0 |= (1<<6);

    /* Loop forever */
	while(1);
}

void EXTI0_IRQHandler(){
	//toggle pin 13 in port A as output register "toggle LED"
	GPIOA_ODR ^= (1<<13);
	//disable pending request register
	EXTI_PR |= (1<<0);
}
