/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//-----------------------------
//Includes
//-----------------------------
#include "STM32F103X6.h"

#include "STM32f103X6_GPIO_Driver.c"

typedef volatile unsigned int vuint32_t;


void GPIO_init(){

	GPIO_PinConfig_t pinconfig;

	//MODE: init GPIOA pin 1 as input(reset state)
	//CNF: make PORTA pin 1 as floating input
	pinconfig.GPIO_PINNumber = GPIO_PIN1;
	pinconfig.GPIO_Mode = GPIO_Mode_IN_Float;
	MCAL_GPIO_init (GPIOA,&pinconfig);


	//MODE: init GPIOB pin 1 as output with max speed = 10MHZ
	//CNF: make PORTB pin 1 as push-pull output
	pinconfig.GPIO_PINNumber = GPIO_PIN1;
	pinconfig.GPIO_Mode = GPIO_Mode_OUT_PP;
	pinconfig.GPIO_Speed = GPIO_Speed_10MHZ;
	MCAL_GPIO_init (GPIOB,&pinconfig);

	/************************************************************/

	//MODE: init GPIOA pin 13 as input(reset state)
	//CNF: make PORTA pin 13 as floating input
	pinconfig.GPIO_PINNumber = GPIO_PIN13;
	pinconfig.GPIO_Mode = GPIO_Mode_IN_Float;
	MCAL_GPIO_init (GPIOA,&pinconfig);

	//MODE: init GPIOB pin 13 as output with max speed = 10MHZ
	//CNF: make PORTB pin 13 as push-pull output
	pinconfig.GPIO_PINNumber = GPIO_PIN13;
	pinconfig.GPIO_Mode = GPIO_Mode_OUT_PP;
	pinconfig.GPIO_Speed = GPIO_Speed_10MHZ;
	MCAL_GPIO_init (GPIOB,&pinconfig);

}


void clock_init(){
	//enable ABP2 clock register
	//enable IO port A clock
	 RCC_GPIOA_CLOCK_EN();

	//enable IO port B clock
	 RCC_GPIOB_CLOCK_EN();
}

void WAIT_ms(uint32_t t){
	uint32_t i,j;
	for(i=0;i<t;i++){
		for(j=0;j<255;j++);
	}
}

int main(void)
{
	clock_init();
	GPIO_init();

    /* Loop forever */
	while(1){
		//mask Port A pin 1 input register
		if(MCAL_GPIO_ReadPIN(GPIOA,GPIO_PIN1)==0)
		{
			MCAL_GPIO_TogglePIN(GPIOB,GPIO_PIN1); 	//toggle led on pin 1 PortB
			while((MCAL_GPIO_ReadPIN(GPIOA,GPIO_PIN1))==0); //single pressing
		}
		//mask Port A pin 13 input register
		if(MCAL_GPIO_ReadPIN(GPIOA,GPIO_PIN13)==1)
		{
			//"multi pressing" toggle led on pin 13 PortB
			MCAL_GPIO_TogglePIN(GPIOB,GPIO_PIN13);

		}
		WAIT_ms(2);	//delay
	}
}
