/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include "STM32f103X6.h"
#include "STM32f103X6_GPIO_Driver.h"
#include "EXTI\STM32F103x6_EXTI_Driver.c"
#include "UART\STM32F103x8_UART_Driver.c"

/* ================================= Global Variables and DataTypes ================================= */
uint16_t  ch;
USART_Config_t uartCFG;
typedef volatile unsigned int vuint32_t;


void WAIT_ms(uint32_t t){
	uint32_t i,j;
	for(i=0;i<t;i++){
		for(j=0;j<255;j++);
	}
}


void clock_init(void)
{
	//enable clock for GPIOA
	RCC_GPIOA_CLOCK_EN();
	//enable clock for GPIOB
	RCC_GPIOB_CLOCK_EN();
	//enable clock for Alternative IO
	RCC_AFIO_CLOCK_EN();
}


/*
 * =====================================
 * 		CallBack Functions
 * =====================================
 */

void USART_IRQ_CallBack (void)
{
	MCAL_USART_ReceiveData(USART1, &ch, disable);
	MCAL_USART_SendData(USART1, &ch, enable);
}


/*
 * =====================================
 * 		Configuration Functions
 * =====================================
 */



void UART_Config(){

	uartCFG.BaudRate = USART_BaudRate_115200;

	uartCFG.Payload_Length = USART_Payload_Length_8B ;

	uartCFG.Parity = USART_NONE_Parity;

	uartCFG.StopBits = USART_1_StopBit;

	uartCFG.HWFlowCTRL = USART_HWFlowCTRL_NONE;

	uartCFG.IRQ_Enable = USART_IRQ_Enable_RXNE;

	uartCFG.P_IRQ_CallBack = USART_IRQ_CallBack ;

	uartCFG.USART_Mode = USART_MODE_TX_RX;


}

int main(void)
{

	clock_init();
	UART_Config();
	MCAL_USART_init(USART1, &uartCFG);
	MCAL_USART_GPIO_SetPins(USART1);

	WAIT_ms(50);


	/* Loop forever */
	while(1){



	}
}
