/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include<stdint.h>
#include<stdlib.h>
typedef volatile unsigned int vuint32_t;
//GPIOA registers
#define GPIOA_BASE 0x40010800 //base address of Port A
#define GPIOA_CRH *(volatile uint32_t*) (GPIOA_BASE+0x04)
#define GPIOA_ODR *(volatile uint32_t*) (GPIOA_BASE+0x0C)

// RCC registers
#define RCC_BASE 0x40021000 //base address of RCC
#define RCC_APB2ENR *(volatile uint32_t*) (RCC_BASE+0x18)
#define RCC_CFGR *(volatile uint32_t*) (RCC_BASE+0x04)
#define RCC_CR  *(volatile uint32_t*) (RCC_BASE+0x0)
void clock_init(){

	//(SW bits) select PLL clock as system clock
	RCC_CFGR |= (0b10<<0) ;

	//(SWS bits) select PLL clock as system clock
	RCC_CFGR |= (0b10<<2) ;

	//(PLLMUL bits) change multiplication factor of PLL clock to x8
	RCC_CFGR |= (0b0110<<18) ;

	//(PPRE2 bits) change high-speed prescaler value of ABP2 HCLK to /4
	RCC_CFGR |= (0b101<<11) ;

	//(PPRE1 bits) change low-speed prescaler value of ABP1 HCLK to /2
	RCC_CFGR |= (0b100<<8) ;

	//(PLLON bits) enable PLL clock
	RCC_CR |= (1<<24) ;
}
int main(void)
{
	clock_init();
	//Enable IO port A clock
	RCC_APB2ENR = 1<<2 ;

	int i;
	//init GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	while(1){
		//enable pin 13 in output data register "open LED"
		GPIOA_ODR |= 1<<13;
		for(i = 0;i<=5000;i++); //delay
		//disable pin 13 in output data register "close LED"
		GPIOA_ODR &= ~(1<<13);
		for(i = 0;i<=5000;i++);
	}
}
